### ISSUE TITLE
pdf无法展示全

### ISSUE THREAD

**Issue by sparGuan** [xxlllq/pdf2img#1]
[2-2020年5月26日语文周测试卷.pdf](https://github.com/xxlllq/pdf2img/files/4686796/2-2020.5.26.pdf)

**Comment by xxlllq** [comment]
> [2-2020年5月26日语文周测试卷.pdf](https://github.com/xxlllq/pdf2img/files/4686796/2-2020.5.26.pdf)

已经修复，并已经将代码更新到项目中。原因是pdf.js不能识别文档中的某些特殊字体。
通过加入如下代码即可以解决：
 PDFJS.cMapUrl = 'https://cdn.jsdelivr.net/npm/pdfjs-dist@2.0.288/cmaps/';
 PDFJS.cMapPacked = true;

可参考：https://github.com/mozilla/pdf.js/issues/9380

**Comment by sparGuan** [comment]
我早就已经解决了，你没用最新的官方的demo去做，自己YY了一套代码
this.pdfData = atob(reader.result.substring(reader.result.indexOf(',') + 1))
        let CMAP_URL = 'https://cdn.jsdelivr.net/npm/pdfjs-dist@2.0.943/cmaps/' // 'https://unpkg.com/pdfjs-dist@2.0.943/cmaps/'
        // 读取base64的pdf流文件
        this.loadingTask = PDFJS.getDocument({
          data: this.pdfData, // PDF base64编码
          cMapUrl: CMAP_URL,
          cMapPacked: true
        })





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xiangxl"<notifications@github.com&gt;; 
发送时间: 2020年6月1日(星期一) 中午11:36
收件人: "xxlllq/pdf2img"<pdf2img@noreply.github.com&gt;; 
抄送: "楠枫di⑥感"<493683987@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [xxlllq/pdf2img] pdf无法展示全 (#1)





  
2-2020年5月26日语文周测试卷.pdf
  
已经修复，并已经将代码更新到项目中。原因是pdf.js不能识别文档中的字体。
 通过如下代码即可以解决：
 PDFJS.cMapUrl = 'https://cdn.jsdelivr.net/npm/pdfjs-dist@2.0.288/cmaps/';
 PDFJS.cMapPacked = true;
