### ISSUE TITLE
可以合并生成一张图片吗

### ISSUE THREAD

**Issue by Mosicol** [xxlllq/pdf2img#4]
现在生成的图片太多，怎么合并成一张

**Comment by xxlllq** [comment]
已增加这个功能，但是图片不易过多（少于20张）效果较好。目前是将canva转成base64的图片进行下载，当图片过多后，浏览器会转成.txt文件下载。也可以自己研究一下其他的方法。

**Comment by Mosicol** [comment]
原来你写的很好了，我在你上一版代码的基础上稍微改了点，就实现了这个需求。
