### ISSUE TITLE
导出整图的清晰度太低

### ISSUE THREAD

**Issue by Olvi73** [xxlllq/pdf2img#6]
导出的整图618kb，放大后会变得特别模糊
chrome自带的网页截图2.61mb，将frame元素隐藏后的直接网页截图，放大后依然特别清晰

**Comment by Olvi73** [comment]
chrome：
![image](https://user-images.githubusercontent.com/46037012/101457552-a60e2f80-3970-11eb-851a-01ef874b5de0.png)
export：
![image](https://user-images.githubusercontent.com/46037012/101457593-b1f9f180-3970-11eb-959f-5c6245b7036c.png)

**Comment by xxlllq** [comment]
![image](https://user-images.githubu

**Comment by xxlllq** [comment]
> 导出的整图618kb，放大后会变得特别模糊
> chrome自带的网页截图2.61mb，将frame元素隐藏后的直接网页截图，放大后依然特别清晰

![image](https://user-images.githubusercontent.com/24718510/101469602-e9bc6580-397f-11eb-994b-cba8d12944a6.png)
可以将index.html中的这个参数值适当调大，此值越大，清晰度越高。

**Comment by Olvi73** [comment]
> > 导出的整图618kb，放大后会变得特别模糊
> > chrome自带的网页截图2.61mb，将frame元素隐藏后的直接网页截图，放大后依然特别清晰
> 
> ![image](https://user-images.githubusercontent.com/24718510/101469602-e9bc6580-397f-11eb-994b-cba8d12944a6.png)
> 可以将index.html中的这个参数值适当调大，此值越大，清晰度越高。

改成10之后放大效果很好，感谢
